### PR TITLE
Provide a better-than-nothing description of the setup

### PR DESCRIPTION
**Pull request by BenWiederhake**
Setting up the account made me "discover" a lot of hidden traps and sharp edges. Let's try to make it less painful for the next user.

### CODE REVIEW

**Comment by heywoodlh** [comment]
Some feedback: I don't use signaldctl so these instructions don't really apply to me. These instructions seem very specific to your setup and wouldn't be _general_ enough to be useful for me. Perhaps the instructions could be more useful if you show how to do the same commands with other clients? For me, I just use bsd-netcat to interact with signald. :)

Also, adduser isn't available on all Linux systems i.e. Arch Linux. Maybe switch adduser to usermod or something that is less distribution specific?

Just some thoughts, hope they are helpful.

**Comment by heywoodlh** [comment]
Also, I would change step four to "log out of your current session." You don't need to restart your machine to apply new group permissions. 

For example, with a server managed via SSH one only need to exit their SSH session and reconnect to apply the new group permissions. Or on a desktop you could just log out of GNOME (or whatever your DE is) and back in.

**Comment by demure** [comment]
Perhaps making it so there was a Header describing the specific setup the instructions for would be good. Then other Sections could be contributed by others. (singald + libpurple-signald + bitlbee user here).

Aside from that, when I was reading the proposed guide it seemed that there where a number of things left unstated and it reads very tersely. I would suggest making the guide a tad more verbose would be beneficial to new Users.

```
## from
6. Try creating a new account. The username *must* be your telephone number.
7. Point your phone at the QR code..

## To
6. Add your a new account.
    * <steps detailing what to click in 'pidgin'>
    * The username *must* be your full international telephone number formatted like `+12223334444` 
7. Scan the generated QR code with signal on your phone to link your account.
```

**Comment by BenWiederhake** [comment]
> these instructions don't really apply to me

The instructions say that you *shouldn't* use it. Therefore, you're following the instructions. Also, you're welcome to add the distribution-specific commands, but how do you expect me to know them for sure? If the instructions say "adduser", then I guess that the user will be clever enough to adapt it for their usecase. :)

> log out of your current session

That's why the instructions explicitly say what really is required and why; I don't think it's a good idea to list *all* the possibilities, because there's infinitely many of them.

> steps detailing what to click in 'pidgin'

Ehh, a little bit intense, but sure.

**Pull request merged**
